### ISSUE TITLE
Client error ... 404 not found

### ISSUE THREAD

**Issue by Sality777** [Gregory-Gerard/RutubeM3U8Scrapper#2]
$ php rutube.php 013d200977aa855e7d313a7d27b84581
[ERROR] Client error: `GET https://rutube.ru/api/play/options/013d200977aa855e7d313a7d27b84581?club_token=[hidden]` resulted in a `404 Not Found` response:
{"detail": {"id": 271, "name": "need_survey", "type": "player_stub", "url": "", "url_stat": "", "image": "", "languages" (truncated...)

example video URL: https://rutube.ru/video/013d200977aa855e7d313a7d27b84581/

**Comment by Gregory-Gerard** [comment]
Hello,

Did you correctly set up your credentials ? I've just tested with your video id and it's working.

![image](https://user-images.githubusercontent.com/56580353/98452057-311ac080-214c-11eb-8f67-563be6cab16f.png)

**Comment by Sality777** [comment]
Hello,

Please excuse me.
It turns out the site demanded to update the profile data to watch the video. Everything is working now. Thanks!
